spring:
  application:
    name: tatarchat

  datasource:
    url: jdbc:postgresql://localhost:5435/tatar_chat_db
    username: tatar-chat-admin
    password: 1
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: public
        jdbc:
          batch_size: 20

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false

app:
  admin:
    email: admin@tatarchat.local
    password: admin123
    display-name: Главный администратор
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970} # 256-bit для HS512
    expiration: 86400000 # 24 часа в миллисекундах
  invite:
    code-length: 8 # Длина генерируемого инвайт-кода

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: your-family-chat@gmail.com # Ваш общий ящик
#    password: xxxx yyyy zzzz wwww        # APP PASSWORD (16 символов без пробелов)
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#        imap:
#          host: imap.gmail.com
#          port: 993
#          ssl:
#            enable: true